### ISSUE TITLE
Pre-Assembled Unit Interest

### ISSUE THREAD

**Issue by Ernegien** [XboxDev/serial-usb-adapter#1]
I've made 20 of these adapters (includes all cables and pin-header for the Xbox LPC) and will be selling them to active XboxDev contributors for $15 USD plus shipping. Non-contributor pricing is $30 USD plus shipping. This will be a bit different however in that those who benefit the most from it will be given priority over others at my discretion so I'd like to get an idea of who's interested first as once they're gone I likely won't be making another batch.

**Note, as described in the README, you'll need either a debug/devkit or a retail v1.0-1.2 motherboard with the capability of soldering a pin-header onto it in order to use this.**

Please let me know via here or Discord if you're interested and whether or not you're located in the EU so I have an idea of how many to ship in bulk there for further distribution.

**Comment by kaosengr** [comment]
I'm interested in obtaining at least 1, 2 if possible.  In the U.S. of A.

**Comment by dans34** [comment]
I would be interested in one
